void init();
void color_noir (int bold);
void color_rouge (int bold);
void color_vert (int bold);
void color_jaune (int bold);
void color_bleu (int bold);
void color_violet (int bold);
void color_cyan (int bold);
void color_blanc (int bold);
void color_reset ();
void print_tokens (char *tokens[],int nb_tokens);
void custom_err (char* msg);
void add_history (char *tokens[], int nb_tokens);
void print_history (int nb);
int len_history ();
char *get_history (int index);
